function get_link() {
    var a = "YUhSMGNITTZMeTloWkhWc2RHUnlaV0Z0TkM1amIyMHZTVVF2T0RRMU9UUXdPVFprTnpJNE9URTVNV0prT1RWaE1EVmhNVE00TmpBeE5EUXZQMkU5TmpJMU1qQTNKbU55UFRJeU5qWTRKbXhwWkQweE16VXhNQ1p0YUQxWGJrcFdWRWhPTWxWdFpGZFpNMXBHWTBoU2FXRXlVbnBoTVVaMlZVaENUVll4V2pWV01WcDRaRWN4ZDFsVlRuaFVhVEEwVG1wcmR5WndQVEFtZEQxVFlXSnlhVzVo";
    a = atob(a);

    return a;
}